version: "3"
services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=news_portal_database'
    networks:
      - my_network

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/news_portal_database'
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge